export const MENU_FETCH_PRODUCTS_BEGIN = 'MENU_FETCH_PRODUCTS_BEGIN';
export const MENU_FETCH_PRODUCTS_SUCCESS = 'MENU_FETCH_PRODUCTS_SUCCESS';
export const MENU_FETCH_PRODUCTS_FAILURE = 'MENU_FETCH_PRODUCTS_FAILURE';
export const MENU_FETCH_PRODUCTS_DISMISS_ERROR = 'MENU_FETCH_PRODUCTS_DISMISS_ERROR';
